added custom validation job [pre-release]

diff --git a/.circleci/continue-config.yml b/.circleci/continue-config.yml
--- a/.circleci/continue-config.yml
+++ b/.circleci/continue-config.yml
@@ -62,11 +62,51 @@ jobs:
                 exit 1
             fi
 
+  validate-chart-version:
+    executor: vfcommon/build-executor
+    parameters:
+      charts:
+        type: string
+      chart_directory:
+        type: string
+        default: "."
+    steps:
+      - checkout
+      - vfcommon/helm-add-repos
+      - run:
+          name: Validate chart version bump
+          command: |
+            #!/bin/bash -e
+            
+            for CHART in ${CHARTS}; do
+              echo "Checking if chart ${CHART} has been modified"
+              LOCAL_CHART="$(cat "${CHART}/Chart.yaml")"
+              CHANNEL="$(yq --raw-output '.annotations."release-repository"' <<< "$LOCAL_CHART")"
+              
+              REPO="voiceflow-charts-s3-$CHANNEL"
+              if [[ "$CHANNEL" == "public" ]]; then
+                REPO="voiceflow-charts-s3"
+              fi
+              
+              LOCAL_VERSION="$(yq --raw-output .version <<< "$LOCAL_CHART")"
+              REMOTE_VERSION="$(helm show chart "$REPO/$(basename $CHART)" | yq --raw-output .version)" || true
+              
+              if [[ -z "$REMOTE_VERSION" ]]; then
+                echo "Chart $CHART does not exist in $REPO. Assuming this is a new chart."
+                continue
+              fi
+              
+              if echo -e "$LOCAL_VERSION\n$REMOTE_VERSION" | sort -c -V 2> /dev/null; then
+                echo "ERROR: Chart version has not been updated. Remote is at $REMOTE_VERSION while local is at $LOCAL_VERSION" >&2
+                exit 1
+              fi
+            done
+
 workflows:
   publish-charts:
     when: << pipeline.parameters.modified_charts >>
     jobs:
-      - vfcommon/validate-chart-version-bump:
+      - validate-chart-version:
           context: dev-test
           charts: << pipeline.parameters.modified_charts >>
           chart_directory: .
@@ -75,7 +115,7 @@ workflows:
           chart_directory: .
           charts: << pipeline.parameters.modified_charts >>
           requires:
-            - vfcommon/validate-chart-version-bump 
+            - validate-chart-version
           filters:
             branches:
               only: master
